# The base image is python 3.12 slim
FROM python:3.12-slim

# Creating the working directory
WORKDIR /app

# Copying the entire code to the Docker image.
COPY . /app

# Exposing the application port
EXPOSE 3306

# Runing the python server, which will return 
# Toronto current time as JSON for GET request
CMD [ "python", "server.py" ]
