version: "3"
services:
  db:
    container_name: mydb
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "gocanada"
    networks:
      - phr_network
  app:
    container_name: PHRapp
    build: ./
    ports:
      - "8080:8080"
    networks:
      - phr_network
    depends_on:
      - db
    environment:
      SQL_HOST: "man"
      SQL_DATABASE: "proj"
      SQL_USER: "manmeet"
      SQL_PASSWORD: "gocanada"

networks:
  phr_network:
    driver: bridge
